### ISSUE TITLE
Bower Dependency

### ISSUE THREAD

**Issue by guygastineau** [exercism/purescript#119]
`npm` wont let me install bower

I am on Arch Linux with `npm version: 6.12.0`
It says that `bower` is deprecated.

Is there any way around this?
I tried to learn `elm`, but it is too painful coming from Haskell, so I really want to try `purescript`

**Comment by guygastineau** [comment]
Nevermind, somehow it just wasn't downloading it before.

I will leave this issue up as it seems like there may be a need to move away from `bower` before too long?  IDK let me know if I should close this issue.

**Comment by connorads** [comment]
@mawis I've created PR #127 to use `spago` instead of `bower`. Let me know what you think.

**Comment by icyrockcom** [comment]
Given that we're on spago now, anything outstanding here or should this be closed at this point?

**Comment by SleeplessByte** [comment]
Nope. I think this can be closed now. If not, re-open.
