### ISSUE TITLE
Recruiting additional maintainers for PureScript

### ISSUE THREAD

**Issue by kytrinyx** [exercism/purescript#120]
We're about to start a big push towards version 3 (v3) of Exercism. This is going to be a really exciting step forward for Exercism, with in-browser coding, new Concept Exercises with automated feedback, improved mentoring and much more.

This to be a big community effort, with the work spread out among hundreds of volunteers across Exercism. One key thing is going to be each track having enough maintainers who have the time to manage that community effort. We are therefore putting out a call for new maintainers to bolster our numbers. We're hoping that our existing maintainers will be able to act as mentors to the newer maintainers we add, and take on a parental role in the tracks.

If you are an existing maintainer, could you please reply to this letting us know that you think you'll have time (2-3hrs/week) to help with this over the next 6 months. If you won't have that time, but still want to be a maintainer and just help where you can instead, please tell us that too. If you have come to the end of the road as a maintainer, then we totally understand that and appreciate all your effort, so just let us know.

For anyone new who's interested in becoming a maintainer, thanks for your interest! Being an Exercism maintainer is also a great opportunity to work with some other smart people, learn more about your language of choice, and gain useful skills and experience that are useful for growing your career in the technical leadership direction. Please write a comment below introducing yourself along with your Exercism handle, and telling us why you're interested in becoming a maintainer, and any relevant experience. We will then evaluate every application and contact you using your exercism email address once we have finished the evaluation process.

Thank you!

See also https://github.com/exercism/exercism/issues/5161

**Comment by mawis** [comment]
I still try to help as much as I can on this. Sometimes my availability changes, so I'm not sure that I can provide 2-3 hrs every week, but still I will be able to provide time for this. E.g. I was following that v3 is being prepared, but me time at the end of last year as limited. I will probably be better in the upcoming time but for sure will also become less again at some point. It always depends on the other workload I have.

So I'm very happy for all volunteers to support this track as well. As we (@kytrinyx) discussed already last year, I'm trying to find more volunteers as well, but it's hard for find PureScript people I my personal environment in general.

**Comment by spicydonuts** [comment]
I'm also available, though it will vary from week to week. I'll try to pay closer attention, but if there are issues not being picked up feel free to assign directly to me as well!

**Comment by aimorris** [comment]
Hi, my name is Adam Morris. I am wishing to help maintain the PureScript track and push it towards v3, as I believe it is a great language to blend JavaScript with functional programming. I've completed about half of the PureScript exercises in exercism, and I've got experience with Haskell. I'll help out where I can.

https://exercism.io/Adam-Morris

**Comment by ErikSchierboom** [comment]
We're closing this issue as it was part of our push to implement the v3 version of this track and v3 has [just been released](https://exercism.org/blog/exercism-v3-has-launched).

New maintainer are always welcome though!
