### ISSUE TITLE
Inconsistent use of unit testing library

### ISSUE THREAD

**Issue by emiel** [exercism/purescript#188]
The practice exercises make use of [test-unit](https://github.com/bodil/purescript-test-unit) while the single concept exercise makes use of [spec](https://github.com/purescript-spec/purescript-spec). As far as I'm aware both are decent libraries.

This currently does not have an effect on the purescript-test-runner but it would be nice to standardize on one library. I see there was a start on setting up TAP for the test-runner. This would nicely abstract away any kind of testing library used but we are not there just yet. ;)

My suggestion would be to port the concept exercise to use 'test-unit' for now.

**Comment by ErikSchierboom** [comment]
That sounds like a good plan. I'd prefer to use a single test library for all exercises.

**Comment by icyrockcom** [comment]
Anything outstanding here?

**Comment by emiel** [comment]
Yes, this been resolved and can be closed now.
