### ISSUE TITLE
Upgrading versions in bower.json does not cause newer versions to be downloaded on CI

### ISSUE THREAD

**Issue by lpil** [exercism/purescript#39]
Seems we're missing an element of cache busting.

**Comment by paf31** [comment]
Can we close this now?

**Comment by lpil** [comment]
I had to manually go onto travis and invalidate the cache, so this is still a problem I believe.

**Comment by icyrockcom** [comment]
@lpil Hm... Interesting, when I merged your changes and pushed, [my travis build](https://travis-ci.org/icyrockcom/xpurescript/builds/222196179) went fine. I did not clean travis cache manually.

**Comment by lpil** [comment]
I busted all of them, not just for my branch.

**Comment by icyrockcom** [comment]
I'm talking about my own fork and its own travis build, see the link I posted. I gather travis does not expunge caches across different profiles even when they are forks, no?

**Comment by lpil** [comment]
Keep it open please @probot-stale[bot] :)
