### ISSUE TITLE
 Pangram test with non-ASCII characters

### ISSUE THREAD

**Issue by TatriX** [exercism/purescript#53]
The readme says `The alphabet used is ASCII, and case insensitive, from 'a' to 'z'
inclusively.`
but there is a test
```purescript
    test "pangram with non ascii characters" do
      Assert.equal true $
        isPangram "Victor jagt zwölf Boxkämpfer quer über den großen Sylter Deich."
```
If I understand the task this test is invalid.

**Comment by icyrockcom** [comment]
Granted, the problem canonical data also contradicts its description:

https://github.com/exercism/problem-specifications/blob/f375051787370bd1af1dd84e8d6c116f07d88ad2/exercises/pangram/canonical-data.json

Unless the idea was to assume that anything non-ASCII, case-insensitive a-z is supposed to be ignored. I've created an issue to address in the problem specification, then we can address here depending on the result: https://github.com/exercism/problem-specifications/issues/842

**Comment by TatriX** [comment]
Hm, but I can't see any non-ASCII like `ä` in the canonical data.

**Comment by icyrockcom** [comment]
Agreed, however the description says:

> from 'a' to 'z' inclusively.

Given that, canonical test cases such as such as:

> 7h3 qu1ck brown fox jumps ov3r 7h3 lazy dog

should be invalid.

I see two interpretations:

- Everything non-ASCII, non-'a'-'z' should be just skipped over
- Everything non-ASCII, non-'a'-'z' should not be in the input

Given by the first, the test cases in our repository are fine. Given the second, the test cases in canonical specification are incorrect.

Another solution is to just pick up the current canonical test cases and not add others. Perhaps that's the best option :)

**Comment by TatriX** [comment]
I understand the readme as "hey, we use ASCII and if there are all 26 letters among other symbols, then it's a pangram". Because obviously usual sentence should have some spaces, commas etc.

**Comment by icyrockcom** [comment]
Sure thing, that works for me. I've prepared a pull request that synchronizes with the current canonical data: https://github.com/exercism/purescript/pull/55.

@paf31, @lpil if this looks good to you, please merge when you get a chance.
