### ISSUE TITLE
UUIDs used across multiple tracks

### ISSUE THREAD

**Issue by houli** [exercism/purescript#78]
Running `bin/configlet lint .` results in errors for all of the UUIDs such as this:
```
-> The following UUID was found in multiple Exercism tracks. Each exercise UUID must be unique across tracks.
83b533f1-a712-4d6a-bc97-505c6e7c9161
```

Not sure how accurate it is, I searched GitHub and only this repository came up as a hit. I've also noticed that the UUIDs I've been generating using `bin/configlet uuid` are longer than the ones that were already in `config.json`

**Comment by icyrockcom** [comment]
This is actually a feature, see https://github.com/exercism/configlet/issues/80 for more details. Just submitted a PR https://github.com/exercism/purescript/pull/80 to fix that.

As for the UUIDs being of different lengths, there's another issue https://github.com/exercism/configlet/issues/99 that might be relevant.
