### ISSUE TITLE
D'oh! I forgot to mention PureScript in this week's newsletter

### ISSUE THREAD

**Issue by kytrinyx** [exercism/purescript#81]
This morning I was like "I know, we've had all sorts of new languages on Exercism in the past few months. Let's talk about that".

And I completely missed PureScript in the list!

I'm so sorry, and I am going to make it the star of next week's newsletter 🌷 

If, in the meantime, you want to write a 2-sentence blurb to entice people to try the language, or if you have any particular things you want me to highlight about contributions you need, then please let me know.

**Comment by kytrinyx** [comment]
Done: https://tinyletter.com/exercism/letters/exercism-behind-the-scenes-we-have-purescript-and-we-are-caremad

✨ 🌻 ✨

**Comment by lpil** [comment]
<3
