### ISSUE TITLE
Syntax highlighting for purescript

### ISSUE THREAD

**Issue by jackhughesweb** [exercism/purescript#94]
This track has not yet specified the file format mapping 
for syntax highlighting in exercism/meta#90

Please provide a mapping of file formats used by your track
in exercism/meta#90 (e.g. md = markdown)

This issue can be closed after this is completed. (Apologies
if you've already done this - this issue was generated
automatically).

**Comment by mawis** [comment]
We currently have no syntax highlighting in the PureScript track.
While prism doesn't support PureScript, I think formatting it with the Haskell formatter might be okay as a work around.

I'll have to figure out whom to ping for this. I'm reopening this issue as a reminder.

**Comment by codingedgar** [comment]
@jackhughesweb I think it looks much better today

**Comment by ErikSchierboom** [comment]
I think we can safely close this.
